"""SpeckleBem - rigorous light scattering from rough surfaces (SIE + fast BEM).

Headless Python front end for the C++ core. See docs/10_python_api.md.
SI units throughout (metres, seconds, V/m, A/m); time convention exp(+jwt).
"""

from ._specklebem import (  # noqa: F401
    DispersiveMaterial,
    Excitation,
    Formulation,
    GaussianBeam,
    HeightMap,
    LogLevel,
    Material,
    MeshQuality,
    Mie,
    PlaneWave,
    Polarization,
    TriangleMesh,
    __version__,
    field_decay_length,
    generate_gaussian_height_map,
    has_blas_lapack,
    has_cuda,
    has_hdf5,
    has_openmp,
    make_icosphere,
    make_mesh_from_height_map,
    make_rough_surface_mesh,
    make_sphere,
    recommend_formulation,
    set_log_level,
    silicon_500nm,
    silver_500nm,
    vacuum,
)
from .rough_surface import RoughSurface

__all__ = [
    "DispersiveMaterial",
    "Excitation",
    "Formulation",
    "GaussianBeam",
    "HeightMap",
    "LogLevel",
    "Material",
    "MeshQuality",
    "Mie",
    "PlaneWave",
    "Polarization",
    "RoughSurface",
    "TriangleMesh",
    "__version__",
    "field_decay_length",
    "generate_gaussian_height_map",
    "has_blas_lapack",
    "has_cuda",
    "has_hdf5",
    "has_openmp",
    "make_icosphere",
    "make_mesh_from_height_map",
    "make_rough_surface_mesh",
    "make_sphere",
    "recommend_formulation",
    "set_log_level",
    "silicon_500nm",
    "silver_500nm",
    "vacuum",
]
